obj-y += gpc.o
obj-$(CONFIG_IMX7_PM_DOMAINS) += gpcv2.o
obj-$(CONFIG_ARCH_FSL_IMX8QM) += mu/
obj-$(CONFIG_ARCH_FSL_IMX8QM) += sc/
obj-$(CONFIG_ARCH_FSL_IMX8QM) += rpmsg/
obj-$(CONFIG_ARCH_FSL_IMX8QM) += pm-domains.o soc-imx8.o
